import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-regal-black dark:text-white mx-2 md:mx-[5rem] min-h-screen flex flex-col flex-grow-1`}
      >
        {/* <Navbar /> */}
        <main className="min-h-[75vh]">{children}</main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
